feat(rule-engine): add update resource support
emqx/emqx-rule-engine pull request #229
Opened 2021-01-25 06:13 UTC by wwhai

2021-01-25 09:15 UTC, turtleDeng commented
Please add test cases.

2021-01-29 09:26 UTC, turtleDeng commented on test/emqx_rule_engine_SUITE.erl
> +    ?assertEqual(ResId, maps:get(id, Resources3)),
Code duplication

2021-01-29 10:34 UTC, HJianBo requested changes

2021-01-29 10:34 UTC, HJianBo commented on src/emqx_rule_engine.erl
> +    lists:foreach(fun(Resource) ->
```suggestion
    lists:foreach(fun refresh_resource/1,
```

2021-01-29 10:34 UTC, HJianBo commented on src/emqx_rule_engine.erl
> +    lists:foreach(fun(Resource) ->
lists:foreach(fun refresh_resource/1,

2021-01-29 10:34 UTC, HJianBo commented on src/emqx_rule_engine_api.erl
> +            return({error, 500, <<"resource dependency by rule:", RuleId/binary>>});
Please fix this error message

2021-01-29 10:34 UTC, HJianBo commented on src/emqx_rule_engine_api.erl
> +            return({error, 500, <<"update resource failed,error info have been written to logfile!">>})
Please fix this error message

2021-01-29 10:34 UTC, HJianBo commented on src/emqx_rule_engine_cli.erl
> +                emqx_ctl:print("update resource failed, reason: ~p!~n", [Reason])
```suggestion
                emqx_ctl:print("Resource update failed: ~0p~n", [Reason])
```

2021-01-29 10:34 UTC, HJianBo commented on test/emqx_rule_engine_SUITE.erl
> +    {ok, #{code := 0, data := Resources3}} = emqx_rule_engine_api:show_resource(#{id => ResId},[]),
```suggestion
    {ok, #{code := 0, data := Resources3}} = emqx_rule_engine_api:show_resource(#{id => ResId}, []),
```

2021-01-29 10:37 UTC, HJianBo commented on src/emqx_rule_engine_api.erl
> +            return({error, 500, <<"resource dependency by rule:", RuleId/binary>>});
4.3.0 also needs to be modified.

2021-01-29 10:54 UTC, HJianBo approved these changes

2021-01-29 10:57 UTC, merged